---
name: E2E Test - Unamanged Cluster

on:
  workflow_dispatch:
  push:
    branches:
      - test-uc-e2e-test

    paths:
      - "**.go"
      - "cli/cmd/plugin/"
      - "**.sh"
      - ".github/workflows/e2e-unmanaged-cluster.yaml"

    tags-ignore:
      - "**"

jobs:
  e2e-unmanaged-cluster-test:
    name: E2E Unmanaged Cluster Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install Ginkgo
        run: |
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
          go get github.com/onsi/gomega/...

      - name: Run Unamanged Cluster E2E Test
        run: |
          make unmanaged-cluster-e2e-test

      - name: Collect tanzu diagnostics data
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: diagnostics-data
          path: |
            bootstrap.*.diagnostics.tar.gz
            management-cluster.*.diagnostics.tar.gz
            workload-cluster.*.diagnostics.tar.gz
