name: Release - Choco Package

on:
  release:
    types:
      - released

jobs:
  update-choco-package:
    name: Update Choco Package
    runs-on: ubuntu-latest
    steps:
      - name: Config credentials
        env:
          GITHUB_TOKEN: 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
        run: |
          git config --global pull.rebase true
          git config --global url."https://git:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
          git config --global user.name aman556
          git config --global user.email amansharma14041998@gmail.com

      - name: Check out code
        uses: actions/checkout@v1

      - name: Update Choco Package
        env:
          GITHUB_TOKEN: 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
        shell: bash
        run: |
          GITHUB_REF="${{ github.ref }}"
          version=${GITHUB_REF/refs\/tags\//}
          ./hack/choco/update-choco-package.sh ${version}
