name: Release - Choco Package

on:
  release:
    types:
      - released

jobs:
  e2e-chocolatey-package-upgrade-test:
    name: Upgrade Test Chocolatey Package
    runs-on: windows-latest
    steps:
      - name: Config credentials
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_ACCESS_TOKEN }}
        run: |
          git config --global pull.rebase true
          git config --global url."https://git:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com


      - name: Check out code
        uses: actions/checkout@v1
        with:
           ssh-private-key: ${{ secrets.AUTOMATION_KEY }}
      - name: Run Upgrade Tests
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_ACCESS_TOKEN }}
        run: |
          cd hack\choco
          $GITHUB_REF="${{github.ref}}"
          $pos=$GITHUB_REF.IndexOf("v")
          $version= $GITHUB_REF.Substring($pos)
          test\choco-upgrade-test.ps1 -version ${version}
